"""drop legacy list table

Revision ID: 1b2e23711528
Revises: c2001d10efbe
Create Date: 2026-09-12 13:46:50.945974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b2e23711528'
down_revision: Union[str, Sequence[str], None] = 'c2001d10efbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Drops the legacy "list" table - an early, superseded prototype of
    what later became custom_lists/list_items/custom_list_entries.
    Confirmed empty (0 rows) and not referenced by any foreign key
    before this migration was written. Unlike every previous
    migration in this environment, this one is a real (non no-op)
    schema change.
    """
    op.drop_table('list')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('imdb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tvdb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_danish_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
