"""add tv series tables: season, episode, disc_contains_episode

Revision ID: ca92db17e42f
Revises: 1b2e23711528
Create Date: 2026-09-12 18:47:58.752991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca92db17e42f'
down_revision: Union[str, Sequence[str], None] = '1b2e23711528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('season_id', sa.BINARY(length=16), nullable=False),
    sa.Column('content_id', sa.BINARY(length=16), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index('idx_season__content_id', 'season', ['content_id'], unique=False)
    op.create_table('episode',
    sa.Column('episode_id', sa.BINARY(length=16), nullable=False),
    sa.Column('season_id', sa.BINARY(length=16), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('original_air_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index('idx_episode__season_id', 'episode', ['season_id'], unique=False)
    op.create_table('disc_contains_episode',
    sa.Column('disc_id', sa.BINARY(length=16), nullable=False),
    sa.Column('episode_id', sa.BINARY(length=16), nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['disc.disc_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.episode_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disc_id', 'episode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disc_contains_episode')
    op.drop_index('idx_episode__season_id', table_name='episode')
    op.drop_table('episode')
    op.drop_index('idx_season__content_id', table_name='season')
    op.drop_table('season')
    # ### end Alembic commands ###
